### ISSUE TITLE
Add Jacoco configuration

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-parent#19]
Add plugin config akin to active-streams-operators/blob/master/pom.xml#L186 into parent.

Once done and released we need to add a profile to each impl/code module we need to measure akin to https://github.com/smallrye/smallrye-reactive-streams-operators/blob/master/implementation/pom.xml#L98

**Comment by michael-schnell** [comment]
Should be a good first step. Things might get more complicated if tests are splitted between "surefire" (simple tests) and "failsafe" (integration tests) Maven plugin. Also multi module projects that have tests in two or more different modules are more difficult to capture correctly with JaCoCo. But I think we should start with above simple setup to get things up and running.

**Comment by jmartisk** [comment]
Another problem will be with Arquillian tests against a full-fledged container because the container runs in a separate JVM so the JaCoCo plugin is unable to instrument the bytecode and you might have to attach the JaCoCo agent to the container separately. I suppose this is something that will be quite dependent on particular project/module.

**Comment by kenfinnigan** [comment]
Ok, I'm no jacoco expert, so whatever steps we can take is better than nothing, and then evolve from there
